extraction:
  cpp:
    after_prepare: 
      - python report.py 88
  cobol:
    after_prepare: 
      - python report.py 88
  csharp:
    after_prepare: 
      - python report.py 88
  java:
    after_prepare: 
      - python report.py 88
  javascript:
    after_prepare: 
      - python report.py 88
  python:
    after_prepare: 
      - python report.py 88
